force-app/main/default/objects/Person__c/fields/Person_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Person_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Person External Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Person__c/fields/Personal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Personal_ID_Number__c</fullName>
    <description>PESEL</description>
    <label>Personal ID Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Working_Hour__c/Working_Hour__c.object-meta.xml
<CustomObject>
    <label>Working Hour</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Working Hour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Working_Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Working_Hour__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Working_Hours</relationshipLabel>
    <relationshipName>Working_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Working_Hour__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Working_Hour__c/fields/Working_Hour_Display__c.field-meta.xml
<CustomField>
    <fullName>Working_Hour_Display__c</fullName>
    <label>Working Hour Display</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DoctorWorkSchedulesCallout.cls
public class DoctorWorkSchedulesCallout implements Schedulable
{
    public class DoctorWorkScheduleWrapper
    {
        public String doctorId;
        public String firstName;
        public String lastName;
        public String pesel;
        public Map<String, DaySchedule> Schedule;
    }
    public class DaySchedule
    {
        public String StartTime;
        public String EndTime;
    }

    @future(callout=true)
    public static void syncDoctorWorkSchedules()
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        request.setEndpoint('callout:MedicalFacilityAPI/services/apexrest/DoctorWorkSchedules');
        request.setMethod('GET');
        
        HttpResponse response = http.send(request);
        
        if(response.getStatusCode() == 200)
        {
            List<DoctorWorkScheduleWrapper> records = (List<DoctorWorkScheduleWrapper>) JSON.deserialize(response.getBody(), List<DoctorWorkScheduleWrapper>.class);
            
            upsertDoctors(records);
            upsertSchedules(records);
        } 
        else
        {
            System.debug(response.getBody());
        }
    }

    private static void upsertDoctors(List<DoctorWorkScheduleWrapper> records)
    {
        List<Person__c> doctorsToUpsert = new List<Person__c>();
        for (DoctorWorkScheduleWrapper rec : records)
        {
            Person__c doctor = new Person__c();
            
            doctor.Person_External_Id__c = rec.doctorId;
            doctor.Name = rec.firstName + ' ' + rec.lastName;
            doctor.Personal_ID_Number__c = rec.pesel;
            
            doctorsToUpsert.add(doctor);
            System.debug(doctor);
        }
        
        System.debug('test');
        upsert doctorsToUpsert Person_External_Id__c;
    }

    private static void upsertSchedules(List<DoctorWorkScheduleWrapper> records)
    {
        Set<String> doctorCodes = new Set<String>();
        for(DoctorWorkScheduleWrapper rec : records)
        {
            doctorCodes.add(rec.doctorId);
        }
        Map<String, Id> doctorCodeToIdMap = new Map<String, Id>();
        for(Person__c doc : [SELECT Id, Person_External_Id__c FROM Person__c WHERE Person_External_Id__c IN : doctorCodes])
        {
            doctorCodeToIdMap.put(doc.Person_External_Id__c, doc.Id);
        }

        List<Working_Hour__c> schedulesToUpsert = new List<Working_Hour__c>();
        
        for (DoctorWorkScheduleWrapper rec : records)
        {
            Id doctorId = doctorCodeToIdMap.get(rec.doctorId);
            for(String day : rec.Schedule.keySet())
            {
                DaySchedule ds = rec.Schedule.get(day);
                Working_Hour__c schedule = new Working_Hour__c();
                
                schedule.Person__c = doctorId;
                schedule.Day__c = day;
                schedule.Start_Time__c = parseTime(ds.StartTime);
                schedule.End_Time__c = parseTime(ds.EndTime);
                schedule.WorKing_Hour_Display__c = ds.startTime + ' - ' + ds.endTime;
                schedule.Unique_Key__c = doctorId + day;

                schedulesToUpsert.add(schedule);
                
                System.debug(schedule);
            }
        	    
        }
        
        System.debug('test');
        upsert schedulesToUpsert unique_Key__c;
    }

    private static Time parseTime(String str) 
    {
        List<String> parts = str.split(':');
        Integer hour = Integer.valueOf(parts[0]);
        Integer min  = Integer.valueOf(parts[1]);
        return Time.newInstance(hour, min, 0, 0);
    }
    
    
    public void execute(SchedulableContext ctx)
    {
        syncDoctorWorkSchedules();
    }
    
    public static void scheduleDailySync(String cronExp, String jobName)
    {
        System.schedule(jobName, cronExp, new DoctorWorkSchedulesCallout());
    }
    
    //DoctorWorkSchedulesCallout.scheduleDailySync('0 0 5 * * ?', 'Dzienna synchronizacja doktorow');
}