force-app/main/default/objects/Doctor_Facility_Assignment__c/Doctor_Facility_Assignment__c.object-meta.xml
<CustomObject>
    <label>Doctor Facility Assignment</label>
    <nameField>
        <label>Doctor Facility Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctor Facility Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor_Facility_Assignment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Doctor Facility Assignments</relationshipLabel>
    <relationshipName>Doctor_Facility_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctor_Facility_Assignment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Doctor Facility Assignments</relationshipLabel>
    <relationshipName>Doctor_Facility_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Medical Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Medical_Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MedicalAppointmentTriggerHandler.cls
public class MedicalAppointmentTriggerHandler {

    public void run() {
        if (Trigger.isBefore) {
            if (Trigger.isInsert || Trigger.isUpdate) {
                validateDoctorFacilityAssignment(Trigger.new);
            }
        }
    }

    private void validateDoctorFacilityAssignment(
        List<Medical_Appointment__c> appointments
    ) {
        Set<Id> doctorIds = new Set<Id>();
        Set<Id> facilityIds = new Set<Id>();

        for (Medical_Appointment__c ma : appointments) {
            if (ma.Doctor__c != null && ma.Medical_Facility__c != null) {
                doctorIds.add(ma.Doctor__c);
                facilityIds.add(ma.Medical_Facility__c);
            }
        }

        if (doctorIds.isEmpty() || facilityIds.isEmpty()) {
            return;
        }

        Set<String> validPairs = new Set<String>();

        for (Doctor_Facility_Assignment__c df : [
            SELECT Person__c, Medical_Facility__c
            FROM Doctor_Facility_Assignment__c
            WHERE Person__c IN :doctorIds
              AND Medical_Facility__c IN :facilityIds
        ]) {
            validPairs.add(df.Person__c + '-' + df.Medical_Facility__c);
        }

        for (Medical_Appointment__c ma : appointments) {
            if (ma.Doctor__c != null && ma.Medical_Facility__c != null) {
                String key = ma.Doctor__c + '-' + ma.Medical_Facility__c;
                if (!validPairs.contains(key)) {
                    ma.addError(
                        'Wybrany lekarz nie pracuje w wybranej placówce.'
                    );
                }
            }
        }
    }
}