force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Medical Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Medical facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Requires_insurance__c.field-meta.xml
<CustomField>
    <fullName>Requires_insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Insurance__c/Medical_Insurance__c.object-meta.xml
<CustomObject>
    <label>Medical Insurance</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Medical Insurance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Insurance__c/fields/Insured_Person__c.field-meta.xml
<CustomField>
    <fullName>Insured_Person__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Insured Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Insurances</relationshipLabel>
    <relationshipName>Medical_Insurances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Insurance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status ubezpieczenia</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckInsuranceTriggerHandler.cls
public class CheckInsuranceTriggerHandler extends TriggerHandler {
    public override void beforeInsert(List<SObject> newList) {
        validate((List<Medical_Appointment__c>) newList,null);
    }
    public override void beforeUpdate(List<SObject> newList,Map<Id,SObject> oldMap){
        validate((List<Medical_Appointment__c>) newList,(Map<Id,Medical_Appointment__c>) oldMap);
    }
    public static void validate(List<Medical_Appointment__c> appointments, Map<Id,Medical_Appointment__c> oldMap){
        Set<Id> patientIds = new Set<Id>();
        Set<Id> facilityIds = new Set<Id>();
        
        for(Medical_Appointment__c ma : appointments) {
            //Sprawdzenie czy był update
            if (oldMap !=null) {
                Medical_Appointment__c oldma = oldMap.get(ma.Id);
                if(oldma != null && oldma.Patient__c == ma.Patient__c && oldma.Medical_facility__c == ma.Medical_facility__c) {
                    continue;
                }
            }
            if(ma.Patient__c !=null && ma.Medical_facility__c != null) {
                patientIds.add(ma.Patient__c);
                facilityIds.add(ma.Medical_facility__c);
            }
        }
        if(patientIds.isEmpty()) return; //równie dobrze facilityIds.isEmpty()
        //Wyszukanie placowek ktore w wizycie zostaly dodane lub zmienione i maja wymagane ubezpieczenie
        Map<Id,Medical_Facility__c> facilities_requires_insurance = new Map<Id, Medical_Facility__c>([Select Id FROM Medical_Facility__c WHERE Id in :facilityIds AND Requires_insurance__c = true]);
        
        if(facilities_requires_insurance.isEmpty()) return;
        
        Set<Id> insuredPatients = new Set<Id>();
        //Wyszukanie pacjentów którzy w wizycie zostali dodanie lub zmienieni i ich ubezpieczenie ma status aktywne
        for(Medical_Insurance__c mi : [Select Insured_Person__c FROM Medical_Insurance__c WHERE Insured_Person__c in :patientIds AND Status__c = 'Active']) {
            insuredPatients.add(mi.Insured_Person__c);
        }
        //jeśli placowka wymaga ubezpieczenia a pacjent go nie ma zostanie przekazany blad
		//kiedy placowka nie wymaga ubezpieczenia to będzie false i caly warunek będzie nieprawdziwy
        for(Medical_Appointment__c ma : appointments) {
            if(facilities_requires_insurance.containsKey(ma.Medical_Facility__c) && !insuredPatients.contains(ma.Patient__c))
            {
                ma.addError('Wybrana placowka wymaga ubezpieczenia, a Pacjent go nie posiada.');
            }
        }
    }
}