force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Medical Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Medical_Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <label>Online</label>
</RecordType>

force-app/main/default/objects/Person__c/fields/Speciazlization__c.field-meta.xml
<CustomField>
    <fullName>Speciazlization__c</fullName>
    <label>Speciazlization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Laryngologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckFirstInternistVisit.cls
public class CheckFirstInternistVisit extends TriggerHandler
{
        
    public override void beforeInsert(List<SObject> newList)
    {
        validate((List<Medical_Appointment__c>) newList, null);
    }
    public override void beforeUpdate(List<SObject> newList, Map<Id, SObject> oldMap) 
    {
        validate
            (
          	(List<Medical_Appointment__c>) newList,
            (Map<Id, Medical_Appointment__c>) oldMap
        );
    }
    
    private static void validate(List<Medical_Appointment__c> appointments,
                                 Map<Id, Medical_Appointment__c> oldMap)
    {
        Set<Id> patientsIdsToCheck = new Set<Id>();
        Set<Id> doctorIdsToCheck = new Set<Id>();
        
        Id onlineRecordTypeId;
        
        Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Medical_Appointment__c.getRecordTypeInfosByDeveloperName();
        if(rtMap.containsKey('Online')) 
        {
            onlineRecordTypeId = rtMap.get('Online').getRecordTypeId();
        }  
        
        for(Medical_Appointment__c appointment : appointments)
        {
            if(oldMap != null && oldMap.containsKey(appointment.Id))
            {
                Medical_Appointment__c oldAppointment = oldMap.get(appointment.Id);
                
                if(oldAppointment.Patient__c == appointment.Patient__c &&
                   oldAppointment.Doctor__c == appointment.Doctor__c &&
                   oldAppointment.RecordTypeId == appointment.RecordTypeId)
                {
                    continue;
                }
            }
            
            if(appointment.RecordTypeId == onlineRecordTypeId)
            {
                patientsIdsToCheck.add(appointment.Patient__c);
                doctorIdsToCheck.add(appointment.Doctor__c);
            }
        }
        
        if (patientsIdsToCheck.isEmpty() || doctorIdsToCheck.isEmpty()) return;
        
        
        
        Map<Id, Integer> internistVisitCountByPatient = new Map<Id, Integer>();
        
        for (AggregateResult counter:
             [ SELECT Patient__c patientId, COUNT(Id) visitCount
              FROM Medical_Appointment__c 
              WHERE Patient__c IN :patientsIdsToCheck
              AND Doctor__r.Speciazlization__c = 'Internist'
              GROUP BY Patient__c
            
             ])
        {
            Id pid = (Id) counter.get('patientId');
            Integer cnt = (Integer) counter.get('visitCount');
            internistVisitCountByPatient.put(pid, cnt);
        }
        
        Map<Id, Person__c> docMap = new Map<Id, Person__c>
            (
                [SELECT Id, Speciazlization__c FROM Person__c WHERE Id IN :doctorIdsToCheck]
            );
        
        
        for(Medical_Appointment__c appointment : appointments)
        {
            if(appointment.RecordTypeId == onlineRecordTypeId)
            {
                Person__c doc = docMap.get(appointment.Doctor__c);
                if(doc.Speciazlization__c == 'Internist')
                {
                	Integer visitCount = internistVisitCountByPatient.get(appointment.Patient__c);
                    if(visitCount == 0 || visitCount == null)
                    {
                        appointment.addError('Pierwsza wizyta u internisty musi być stacjonarnie');
                    }    
                }
            }
        }
    }
}