force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Contact email of the facility</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Medical_Facility_Code__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility_Code__c</fullName>
    <description>Unique facility identifier</description>
    <displayFormat>FAC-{0000}</displayFormat>
    <label>Medical Facility Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number of the facility</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Medical_Facility_Opening_Hour__c/Medical_Facility_Opening_Hour__c.object-meta.xml
<CustomObject>
    <label>Medical Facility Opening Hour</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opening Hour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Facility Opening Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility_Opening_Hour__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poniedziałek</fullName>
            </value>
            <value>
                <fullName>Wtorek</fullName>
            </value>
            <value>
                <fullName>Środa</fullName>
            </value>
            <value>
                <fullName>Czwartek</fullName>
            </value>
            <value>
                <fullName>Piątek</fullName>
            </value>
            <value>
                <fullName>Sobota</fullName>
            </value>
            <value>
                <fullName>Niedziela</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Facility_Opening_Hour__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipName>Medical_Facility_Opening_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Facility_Opening_Hour__c/fields/Opening_Hour__c.field-meta.xml
<CustomField>
    <fullName>Opening_Hour__c</fullName>
    <label>Opening Hour</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Facility_Opening_Hour__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MedicalFacilityCallout.cls
public class MedicalFacilityCallout
{
    
    @future(callout=true)
    public static void syncFacility()
    {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        
        request.setEndpoint('callout:MedicalFacilityAPI/services/apexrest/MedicalFacilities');
        request.setMethod('GET');
        System.debug(request);
        
        HttpResponse response = http.send(request);
        System.debug('Test');
        System.debug(response);
        
        if(response.getStatusCode() == 200)
        {
            List<Object> records = (List<Object>) JSON.deserializeUntyped(response.getBody());
            
            upsertMedicalFacilities(records);
            upsertMedicalFacilitiesHours(records);
        } 
        else
        {
            System.debug(response.getBody());
        }
    }
    
    private static void upsertMedicalFacilities(List<Object> records)
    {
        System.debug(records.size());
        List<Medical_Facility__c> facilitiesToUpsert = new List<Medical_Facility__c>();
        for (Object obj : records)
        {
            System.debug(obj);
            Map<String, Object> data = (Map<String, Object>) obj;
            Medical_Facility__c facility = new Medical_Facility__c();
            
            facility.Medical_Facility_Code__c = ((String) data.get('Id')).trim();
            facility.Name = (String) data.get('Name');
            facility.Email__c = (String) data.get('Email');
            facility.Phone_Number__c = (String) data.get('Phone');
            
            Map<String, Object> addresMap = (Map<String, Object>) data.get('Address');
            if(addresMap != null)
            {
                facility.Medical_Facility_Address__Street__s = (String) addresMap.get('Street');
                facility.Medical_Facility_Address__PostalCode__s = (String) addresMap.get('PostalCode');
                facility.Medical_Facility_Address__City__s = (String) addresMap.get('City');
                facility.Medical_Facility_Address__CountryCode__s = 'PL';
            }
            
            System.debug(facility);
            facilitiesToUpsert.add(facility);
        }
        
        upsert facilitiesToUpsert Medical_Facility_Code__c;
    }
   
    
    private static void upsertMedicalFacilitiesHours(List<Object> records)
    {
        List<Medical_Facility_Opening_Hour__c> hoursToUpsert = new List<Medical_Facility_Opening_Hour__c>();
        Map<String, Id> facilityMap = new Map<String, Id>();
        for (Medical_Facility__c mf : [SELECT Id, Medical_Facility_Code__c FROM Medical_Facility__c])
        {
            facilityMap.put(mf.Medical_Facility_Code__c, mf.Id);
        }
        
        for(Object obj : records)
        {
            Map<String, Object> data = (Map<String, Object>) obj;
            
            String facilityCode = (String) data.get('Id');
            Id facilityId = facilityMap.get(facilityCode);
            
            Map<String, Object> openingHours = (Map<String, Object>) data.get('OpeningHours');
            
            for(String day : openingHours.keySet())
            {
                Medical_Facility_Opening_Hour__c hour = new Medical_Facility_Opening_Hour__c();
                hour.Medical_Facility__c = facilityId;
                hour.Day__c = day;
                hour.Opening_Hour__c = (String) openingHours.get(day);
                hour.Unique_Key__c = facilityCode + day;
                hoursToUpsert.add(hour);
            }
        }
        
        upsert hoursToUpsert Unique_Key__c;
    }
}